openapi: 3.0.0
info:
  title: Home Library Service
  description: Home music library service
  version: 1.0.0

servers:
  - url: /

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        login:
          type: string
        version:
          type: integer
        createdAt:
          type: integer
        updatedAt:
          type: integer
      required:
        - id
        - login
        - version
        - createdAt
        - updatedAt

    Artist:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        grammy:
          type: boolean
      required:
        - id
        - name
        - grammy

    Album:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        year:
          type: integer
        artistId:
          type: string
          format: uuid
          nullable: true
      required:
        - id
        - name
        - year

    Track:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        artistId:
          type: string
          format: uuid
          nullable: true
        albumId:
          type: string
          format: uuid
          nullable: true
        duration:
          type: integer
      required:
        - id
        - name
        - duration

    Favorites:
      type: object
      properties:
        artists:
          type: array
          items:
            $ref: "#/components/schemas/Artist"
        albums:
          type: array
          items:
            $ref: "#/components/schemas/Album"
        tracks:
          type: array
          items:
            $ref: "#/components/schemas/Track"

paths:
  ############################
  # USER ROUTES
  ############################
  /user:
    get:
      tags: [User]
      summary: Get all users
      responses:
        200:
          description: All users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"

    post:
      tags: [User]
      summary: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required: [login, password]
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Bad request. Missing required fields.

  /user/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      tags: [User]
      summary: Get user by id
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid id (not uuid)
        404:
          description: User not found

    put:
      tags: [User]
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
              required: [oldPassword, newPassword]
      responses:
        200:
          description: User updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid id (not uuid)
        403:
          description: Old password is wrong
        404:
          description: User not found

    delete:
      tags: [User]
      summary: Delete user
      responses:
        204:
          description: User deleted
        400:
          description: Invalid id (not uuid)
        404:
          description: User not found

  ############################
  # TRACK ROUTES
  ############################
  /track:
    get:
      tags: [Track]
      summary: Get all tracks
      responses:
        200:
          description: All tracks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Track"

    post:
      tags: [Track]
      summary: Create track
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                artistId:
                  type: string
                  nullable: true
                albumId:
                  type: string
                  nullable: true
                duration:
                  type: integer
              required: [name, duration]
      responses:
        201:
          description: Track created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        400:
          description: Bad request. Missing required fields.

  /track/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      tags: [Track]
      summary: Get track by id
      responses:
        200:
          description: Track found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        400:
          description: Invalid id (not uuid)
        404:
          description: Track not found

    put:
      tags: [Track]
      summary: Update track
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                artistId: { type: string, nullable: true }
                albumId: { type: string, nullable: true }
                duration: { type: integer }
              required: [name, duration]
      responses:
        200:
          description: Track updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Track"
        400:
          description: Invalid id (not uuid)
        404:
          description: Track not found

    delete:
      tags: [Track]
      summary: Delete track
      responses:
        204:
          description: Track deleted
        400:
          description: Invalid id (not uuid)
        404:
          description: Track not found

  ############################
  # ARTIST ROUTES
  ############################
  /artist:
    get:
      tags: [Artist]
      summary: Get all artists
      responses:
        200:
          description: All artists
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Artist"

    post:
      tags: [Artist]
      summary: Create artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                grammy: { type: boolean }
              required: [name, grammy]
      responses:
        201:
          description: Artist created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artist"
        400:
          description: Bad request. Missing required fields.

  /artist/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      tags: [Artist]
      summary: Get artist by id
      responses:
        200:
          description: Artist found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artist"
        400:
          description: Invalid id (not uuid)
        404:
          description: Artist not found

    put:
      tags: [Artist]
      summary: Update artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                grammy: { type: boolean }
              required: [name, grammy]
      responses:
        200:
          description: Artist updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Artist"
        400:
          description: Invalid id (not uuid)
        404:
          description: Artist not found

    delete:
      tags: [Artist]
      summary: Delete artist
      responses:
        204:
          description: Artist deleted
        400:
          description: Invalid id (not uuid)
        404:
          description: Artist not found

  ############################
  # ALBUM ROUTES
  ############################
  /album:
    get:
      tags: [Album]
      summary: Get all albums
      responses:
        200:
          description: All albums
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Album"

    post:
      tags: [Album]
      summary: Create album
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                year: { type: integer }
                artistId: { type: string, nullable: true }
              required: [name, year]
      responses:
        201:
          description: Album created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Album"
        400:
          description: Bad request. Missing required fields.

  /album/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string

    get:
      tags: [Album]
      summary: Get album by id
      responses:
        200:
          description: Album found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Album"
        400:
          description: Invalid id (not uuid)
        404:
          description: Album not found

    put:
      tags: [Album]
      summary: Update album
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                year: { type: integer }
                artistId: { type: string, nullable: true }
              required: [name, year]
      responses:
        200:
          description: Album updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Album"
        400:
          description: Invalid id (not uuid)
        404:
          description: Album not found

    delete:
      tags: [Album]
      summary: Delete album
      responses:
        204:
          description: Album deleted
        400:
          description: Invalid id (not uuid)
        404:
          description: Album not found

  ############################
  # FAVORITES ROUTES
  ############################
  /favs:
    get:
      tags: [Favorites]
      summary: Get all favorites
      responses:
        200:
          description: All favorites data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Favorites"

  /favs/track/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }

    post:
      tags: [Favorites]
      summary: Add track to favorites
      responses:
        201:
          description: Added successfully
        400:
          description: Invalid id (not uuid)
        422:
          description: Track does not exist

    delete:
      tags: [Favorites]
      summary: Remove track from favorites
      responses:
        204:
          description: Removed successfully
        400:
          description: Invalid id (not uuid)
        404:
          description: Track not in favorites

  /favs/album/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }

    post:
      tags: [Favorites]
      summary: Add album to favorites
      responses:
        201:
          description: Added successfully
        400:
          description: Invalid id (not uuid)
        422:
          description: Album does not exist

    delete:
      tags: [Favorites]
      summary: Remove album from favorites
      responses:
        204:
          description: Removed successfully
        400:
          description: Invalid id (not uuid)
        404:
          description: Album not in favorites

  /favs/artist/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema: { type: string }

    post:
      tags: [Favorites]
      summary: Add artist to favorites
      responses:
        201:
          description: Added successfully
        400:
          description: Invalid id (not uuid)
        422:
          description: Artist does not exist

    delete:
      tags: [Favorites]
      summary: Remove artist from favorites
      responses:
        204:
          description: Removed successfully
        400:
          description: Invalid id (not uuid)
        404:
          description: Artist not in favorites

